"""Added filetype column

Revision ID: 6d0fb8fd7d04
Revises: 
Create Date: 2024-11-28 12:02:41.110423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d0fb8fd7d04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filetype', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('filepath', sa.String(length=150), nullable=False))
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('uploader',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_column('size')
        batch_op.drop_column('extension')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extension', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('size', sa.INTEGER(), nullable=False))
        batch_op.alter_column('uploader',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('filename',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('filepath')
        batch_op.drop_column('filetype')

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), nullable=False),
    sa.Column('password', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
